"""
Code Generation Templates

Jinja2 templates for generating consistent, production-ready code.
"""
from typing import List, Dict, Any
from jinja2 import Template


class TemplateEngine:
    """Renders code templates for various code types."""
    
    # ============ FastAPI Router Template ============
    FASTAPI_ROUTER_TEMPLATE = Template('''
"""
{{ model_name }} API Endpoints
Auto-generated by Cerebrum Self-Coding System
"""
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from pydantic import BaseModel, Field

from ..database import get_db
from ..models import {{ model_name }} as {{ model_name }}DB

router = APIRouter(prefix="{{ endpoint_path }}", tags=["{{ model_name.lower() }}"])


# ============ Pydantic Models ============

class {{ model_name }}Create(BaseModel):
    {% for field in fields %}{{ field.name }}: {% if field.type == "string" %}str{% elif field.type == "integer" %}int{% elif field.type == "float" %}float{% elif field.type == "boolean" %}bool{% else %}Any{% endif %}{% if not field.required %} = None{% endif %}
    {% if field.description %}    Field(..., description="{{ field.description }}"){% endif %}
    {% endfor %}


class {{ model_name }}Update(BaseModel):
    {% for field in fields %}{{ field.name }}: Optional[{% if field.type == "string" %}str{% elif field.type == "integer" %}int{% elif field.type == "float" %}float{% elif field.type == "boolean" %}bool{% else %}Any{% endif %}] = None
    {% endfor %}


class {{ model_name }}Response(BaseModel):
    id: str
    {% for field in fields %}{{ field.name }}: {% if field.type == "string" %}str{% elif field.type == "integer" %}int{% elif field.type == "float" %}float{% elif field.type == "boolean" %}bool{% else %}Any{% endif %}
    {% endfor %}
    created_at: str
    updated_at: str

    class Config:
        from_attributes = True


# ============ CRUD Operations ============

{% if "create" in operations %}
@router.post("", response_model={{ model_name }}Response)
async def create_{{ model_name.lower() }}(
    data: {{ model_name }}Create,
    db: Session = Depends(get_db)
):
    \"\"\"Create a new {{ model_name }}.\"\"\"
    db_item = {{ model_name }}DB(**data.model_dump())
    db.add(db_item)
    db.commit()
    db.refresh(db_item)
    return db_item
{% endif %}

{% if "list" in operations %}
@router.get("", response_model=List[{{ model_name }}Response])
async def list_{{ model_name.lower() }}s(
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    \"\"\"List all {{ model_name }}s with pagination.\"\"\"
    return db.query({{ model_name }}DB).offset(skip).limit(limit).all()
{% endif %}

{% if "read" in operations %}
@router.get("/{item_id}", response_model={{ model_name }}Response)
async def get_{{ model_name.lower() }}(
    item_id: str,
    db: Session = Depends(get_db)
):
    \"\"\"Get a {{ model_name }} by ID.\"\"\"
    item = db.query({{ model_name }}DB).filter({{ model_name }}DB.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="{{ model_name }} not found")
    return item
{% endif %}

{% if "update" in operations %}
@router.put("/{item_id}", response_model={{ model_name }}Response)
async def update_{{ model_name.lower() }}(
    item_id: str,
    data: {{ model_name }}Update,
    db: Session = Depends(get_db)
):
    \"\"\"Update a {{ model_name }}.\"\"\"
    item = db.query({{ model_name }}DB).filter({{ model_name }}DB.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="{{ model_name }} not found")
    
    for field, value in data.model_dump(exclude_unset=True).items():
        setattr(item, field, value)
    
    db.commit()
    db.refresh(item)
    return item
{% endif %}

{% if "delete" in operations %}
@router.delete("/{item_id}")
async def delete_{{ model_name.lower() }}(
    item_id: str,
    db: Session = Depends(get_db)
):
    \"\"\"Delete a {{ model_name }}.\"\"\"
    item = db.query({{ model_name }}DB).filter({{ model_name }}DB.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="{{ model_name }} not found")
    
    db.delete(item)
    db.commit()
    return {"success": True, "message": "{{ model_name }} deleted"}
{% endif %}
''')

    # ============ React Component Template ============
    REACT_COMPONENT_TEMPLATE = Template('''
/**
 * {{ component_name }} Component
 * Auto-generated by Cerebrum Self-Coding System
 */
import React, { useState, useEffect } from 'react';
{% if api_endpoints %}import { apiClient } from '../api/client';{% endif %}

{% if styling == "tailwind" %}
// Tailwind CSS classes
{% endif %}

// ============ Types ============

{% for prop in props %}
interface {{ component_name }}Props {
  {% for prop in props %}{{ prop.name }}{% if not prop.required %}?{% endif %}: {{ prop.type }};
  {% endfor %}
}
{% endfor %}

// ============ Component ============

export const {{ component_name }}: React.FC<{{ component_name }}Props> = ({ 
  {% for prop in props %}{{ prop.name }}{% if not prop.required %} = {% if prop.type == "string" %}''{% elif prop.type == "number" %}0{% elif prop.type == "boolean" %}false{% else %}undefined{% endif %}{% endif %},
  {% endfor %}
}) => {
  // ============ State ============
  {% for field in state_fields %}
  const [{{ field.name }}, set{{ field.name | title }}] = useState<{{ field.type }}>({% if field.initial_value %}{{ field.initial_value }}{% elif field.type == "string" %}''{% elif field.type == "number" %}0{% elif field.type == "boolean" %}false{% elif field.type == "array" %}[]{% else %}null{% endif %});
  {% endfor %}
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // ============ Effects ============
  {% if api_endpoints %}
  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    setLoading(true);
    try {
      {% for endpoint in api_endpoints %}
      // const response = await apiClient.get('{{ endpoint }}');
      {% endfor %}
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLoading(false);
    }
  };
  {% endif %}

  // ============ Handlers ============
  
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      // TODO: Implement submit logic
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLoading(false);
    }
  };

  // ============ Render ============
  
  return (
    {% if styling == "tailwind" %}
    <div className="p-6 bg-white rounded-lg shadow">
      <h2 className="text-2xl font-bold mb-4">{{ component_name }}</h2>
      
      {error && (
        <div className="mb-4 p-4 bg-red-100 text-red-700 rounded">
          {error}
        </div>
      )}
      
      {loading ? (
        <div className="flex justify-center py-8">
          <div className="animate-spin h-8 w-8 border-4 border-blue-500 border-t-transparent rounded-full" />
        </div>
      ) : (
        <div>
          {/* TODO: Implement component UI */}
          <p className="text-gray-600">Component content goes here</p>
        </div>
      )}
    </div>
    {% else %}
    <div className="{{ component_name | lower }}-container">
      <h2>{{ component_name }}</h2>
      
      {error && <div className="error">{error}</div>}
      
      {loading ? (
        <div className="loading">Loading...</div>
      ) : (
        <div>
          {/* TODO: Implement component UI */}
          <p>Component content goes here</p>
        </div>
      )}
    </div>
    {% endif %}
  );
};

export default {{ component_name }};
''')

    # ============ SQLAlchemy Model Template ============
    SQLALCHEMY_MODEL_TEMPLATE = Template('''
"""
{{ model_name }} Database Model
Auto-generated by Cerebrum Self-Coding System
"""
from datetime import datetime
from sqlalchemy import Column, String, DateTime, Integer, Float, Boolean, ForeignKey, Index
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class {{ model_name }}(Base):
    \"\"\"
    {{ model_name }} database model.
    \"\"\"
    __tablename__ = "{{ table_name }}"
    
    {% for column in columns %}
    {% if column.primary_key %}
    {{ column.name }} = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    {% else %}
    {{ column.name }} = Column(
        {% if column.type == "string" %}String(255){% elif column.type == "integer" %}Integer{% elif column.type == "float" %}Float{% elif column.type == "boolean" %}Boolean{% elif column.type == "datetime" %}DateTime{% else %}String(255){% endif %}
        {% if not column.nullable %}, nullable=False{% endif %}
        {% if column.default %}, default={{ column.default }}{% endif %}
    {% if column.index %}    {% endif %}{% if column.index %}, index=True{% endif %}
    )
    {% endif %}
    {% endfor %}
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    {% for rel in relationships %}
    {% if rel.type == "one-to-many" %}
    {{ rel.name }} = relationship("{{ rel.target }}", back_populates="{{ model_name | lower }}")
    {% elif rel.type == "many-to-one" %}
    {{ rel.name }}_id = Column(String(36), ForeignKey("{{ rel.target | lower }}s.id"))
    {{ rel.name }} = relationship("{{ rel.target }}", back_populates="{{ model_name | lower }}s")
    {% endif %}
    {% endfor %}
    
    def __repr__(self):
        return f"<{{ model_name }}(id={self.id})>"
    
    def to_dict(self):
        \"\"\"Convert model to dictionary.\"\"\"
        return {
            {% for column in columns %}"{{ column.name }}": self.{{ column.name }},
            {% endfor %}"created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
''')

    # ============ Alembic Migration Template ============
    ALEMBIC_MIGRATION_TEMPLATE = Template('''
"""
{{ revision_name }}
Auto-generated by Cerebrum Self-Coding System

Revision ID: ${revision}
Revises: ${down_revision}
Create Date: ${create_date}
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers
revision = '${revision}'
down_revision = '${down_revision}'
branch_labels = None
depends_on = None


def upgrade():
    {% for op in operations %}
    {% if op.type == "create_table" %}
    # Create {{ op.table_name }} table
    op.create_table(
        '{{ op.table_name }}',
        {% for col in op.columns %}
        sa.Column('{{ col.name }}', 
            {% if col.type == "string" %}sa.String(255){% elif col.type == "integer" %}sa.Integer(){% elif col.type == "float" %}sa.Float(){% elif col.type == "boolean" %}sa.Boolean(){% elif col.type == "datetime" %}sa.DateTime(){% else %}sa.String(255){% endif %},
            {% if col.primary_key %}primary_key=True{% endif %}
            {% if not col.nullable %}, nullable=False{% endif %}
        ),
        {% endfor %}
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
    )
    {% elif op.type == "drop_table" %}
    # Drop {{ op.table_name }} table
    op.drop_table('{{ op.table_name }}')
    {% elif op.type == "add_column" %}
    # Add column to {{ op.table_name }}
    op.add_column('{{ op.table_name }}', sa.Column('{{ op.column.name }}', sa.String(255)))
    {% elif op.type == "drop_column" %}
    # Drop column from {{ op.table_name }}
    op.drop_column('{{ op.table_name }}', '{{ op.column_name }}')
    {% elif op.type == "create_index" %}
    # Create index on {{ op.table_name }}
    op.create_index('{{ op.index_name }}', '{{ op.table_name }}', ['{{ op.column_name }}'])
    {% elif op.type == "drop_index" %}
    # Drop index from {{ op.table_name }}
    op.drop_index('{{ op.index_name }}', '{{ op.table_name }}')
    {% endif %}
    {% endfor %}


def downgrade():
    {% for op in operations|reverse %}
    {% if op.type == "create_table" %}
    op.drop_table('{{ op.table_name }}')
    {% elif op.type == "drop_table" %}
    # Recreate {{ op.table_name }} table (manual implementation needed)
    pass
    {% elif op.type == "add_column" %}
    op.drop_column('{{ op.table_name }}', '{{ op.column.name }}')
    {% elif op.type == "drop_column" %}
    # Re-add column (manual implementation needed)
    pass
    {% elif op.type == "create_index" %}
    op.drop_index('{{ op.index_name }}', '{{ op.table_name }}')
    {% elif op.type == "drop_index" %}
    # Recreate index (manual implementation needed)
    pass
    {% endif %}
    {% endfor %}
''')

    def render_fastapi_router(
        self,
        endpoint_path: str,
        model_name: str,
        fields: List[Dict[str, Any]],
        operations: List[str]
    ) -> str:
        """Render FastAPI router template."""
        return self.FASTAPI_ROUTER_TEMPLATE.render(
            endpoint_path=endpoint_path,
            model_name=model_name,
            fields=fields,
            operations=operations
        )
    
    def render_react_component(
        self,
        component_name: str,
        props: List[Dict[str, Any]] = None,
        state_fields: List[Dict[str, Any]] = None,
        api_endpoints: List[str] = None,
        styling: str = "tailwind"
    ) -> str:
        """Render React component template."""
        return self.REACT_COMPONENT_TEMPLATE.render(
            component_name=component_name,
            props=props or [],
            state_fields=state_fields or [],
            api_endpoints=api_endpoints or [],
            styling=styling
        )
    
    def render_sqlalchemy_model(
        self,
        table_name: str,
        model_name: str,
        columns: List[Dict[str, Any]],
        relationships: List[Dict[str, Any]] = None
    ) -> str:
        """Render SQLAlchemy model template."""
        return self.SQLALCHEMY_MODEL_TEMPLATE.render(
            table_name=table_name,
            model_name=model_name,
            columns=columns,
            relationships=relationships or []
        )
    
    def render_alembic_migration(
        self,
        revision_name: str,
        operations: List[Dict[str, Any]]
    ) -> str:
        """Render Alembic migration template."""
        import uuid
        from datetime import datetime
        
        return self.ALEMBIC_MIGRATION_TEMPLATE.render(
            revision_name=revision_name,
            operations=operations,
            revision=str(uuid.uuid4())[:12],
            down_revision=None,
            create_date=datetime.utcnow().isoformat()
        )
